package com.saleh12340.quickdailynotebook
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.media.MediaPlayer;import android.media.MediaRecorder;import android.net.Uri;import android.view.*;import android.widget.*;import java.io.File;import java.text.SimpleDateFormat;import java.util.*
class NoteActivity:Activity(){
 lateinit var db:Db;lateinit var body:LinearLayout;lateinit var title:EditText;var id=0L;val blocks=mutableListOf<Block>();var recorder:MediaRecorder?=null;var recordingFile:File?=null
 override fun onCreate(b:Bundle?){super.onCreate(b);id=intent.getLongExtra("id",0);db=Db(this);window.decorView.layoutDirection=View.LAYOUT_DIRECTION_RTL;render()}
 fun render(){val root=LinearLayout(this);root.orientation=LinearLayout.VERTICAL;root.setPadding(14,10,14,14);root.setBackgroundColor(Color.rgb(255,253,247))
 val bar=LinearLayout(this);val back=Button(this).apply{text="←";setOnClickListener{save();finish()}};bar.addView(back,LinearLayout.LayoutParams(55,55));title=EditText(this).apply{setText(db.title(id));hint="عنوان الملاحظة";textSize=20f;textDirection=View.TEXT_DIRECTION_RTL;setSingleLine(false)};bar.addView(title,LinearLayout.LayoutParams(0,60,1f));val more=Button(this).apply{text="⋮";setOnClickListener{menu(this)}};bar.addView(more,LinearLayout.LayoutParams(55,55));root.addView(bar)
 val date=TextView(this).apply{text=SimpleDateFormat("EEEE، d MMMM yyyy",Locale("ar")).format(Date());textSize=15f;setPadding(8,0,8,8)};root.addView(date)
 val tools=LinearLayout(this);listOf(Button(this).apply{text="🎙";setOnClickListener{record()}},Button(this).apply{text="🖼";setOnClickListener{pickImage()}},Button(this).apply{text="مشاركة";setOnClickListener{shareNote()}},Button(this).apply{text="طباعة";setOnClickListener{printNote()}}).forEach{tools.addView(it)};root.addView(tools)
 body=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val sv=ScrollView(this);sv.addView(body);root.addView(sv,LinearLayout.LayoutParams(-1,0,1f));setContentView(root);loadBlocks();if(blocks.isEmpty())addText()}
 fun lineEdit(text:String=""):EditText{val e=EditText(this).apply{setText(text);textSize=18f;gravity=Gravity.TOP or Gravity.RIGHT;textDirection=View.TEXT_DIRECTION_RTL;setPadding(8,7,8,7);background=getDrawable(R.drawable.paper_line);minHeight=54;setSingleLine(false)};body.addView(e,LinearLayout.LayoutParams(-1,-2));return e}
 fun addText(text:String=""){lineEdit(text)}
 fun loadBlocks(){blocks.clear();body.removeAllViews();db.blocks(id).forEach{b->blocks.add(b);when(b.type){"TEXT"->lineEdit(b.text);"AUDIO"->audioView(b);"IMAGE"->imageView(b)}}}
 fun save(){val out=mutableListOf<Block>();for(i in 0 until body.childCount){val v=body.getChildAt(i);when(v){is EditText->out.add(Block(noteId=id,type="TEXT",position=i,text=v.text.toString()));else->{val b=v.tag as? Block;if(b!=null)out.add(b.copy(position=i))}}};blocks.clear();blocks.addAll(out);db.saveTitle(id,title.text.toString());db.replaceBlocks(id,blocks)}
 fun menu(v:View){PopupMenu(this,v).apply{menu.add("سطر نص جديد");menu.add("حذف الملاحظة");menu.add("نسخ الملاحظة");setOnMenuItemClickListener{when(it.title.toString()){"سطر نص جديد"->addText();"حذف الملاحظة"->db.delete(id).also{finish()};"نسخ الملاحظة"->copyNote()};true}}.show()}
 fun copyNote(){val s=buildText();(getSystemService(CLIPBOARD_SERVICE) as android.content.ClipboardManager).setPrimaryClip(android.content.ClipData.newPlainText("دفتر يومي",s));Toast.makeText(this,"تم نسخ الملاحظة",Toast.LENGTH_SHORT).show()}
 fun buildText():String{save();return buildString{append(title.text).append("\n");blocks.forEach{when(it.type){"TEXT"->append(it.text).append("\n");"AUDIO"->append("[تسجيل صوتي: ").append(it.name).append("]\n");"IMAGE"->append("[صورة: ").append(it.name).append("]\n")}}}}
 fun shareNote(){val i=Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,buildText());startActivity(Intent.createChooser(i,"مشاركة الملاحظة"))}
 fun record(){if(recorder!=null){try{recorder?.stop()}catch(_:Exception){};recorder?.release();recorder=null;recordingFile?.let{f->blocks.add(Block(noteId=id,type="AUDIO",position=blocks.size,uri=f.absolutePath,name="تسجيل "+SimpleDateFormat("HH:mm",Locale.getDefault()).format(Date())))};save();loadBlocks();Toast.makeText(this,"تم حفظ التسجيل",Toast.LENGTH_SHORT).show();return};if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(arrayOf(Manifest.permission.RECORD_AUDIO),7);return};recordingFile=File(filesDir,"audio_"+System.currentTimeMillis()+".m4a");recorder=MediaRecorder(this).apply{setAudioSource(MediaRecorder.AudioSource.MIC);setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);setAudioEncoder(MediaRecorder.AudioEncoder.AAC);setOutputFile(recordingFile!!.absolutePath);prepare();start()};Toast.makeText(this,"🔴 جاري التسجيل — اضغط لإيقافه",Toast.LENGTH_LONG).show()}
 fun audioView(b:Block){val row=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(10,5,10,5);background=getDrawable(R.drawable.paper_line)};val play=Button(this).apply{text="▶";setOnClickListener{MediaPlayer().apply{setDataSource(b.uri);prepare();start();setOnCompletionListener{release()}}}};row.addView(play);row.addView(TextView(this).apply{text="🎙 "+b.name;textSize=16f});row.tag=b;body.addView(row)}
 fun imageView(b:Block){val row=TextView(this).apply{text="📎 "+b.name;textSize=17f;setPadding(12,14,12,14);background=getDrawable(R.drawable.paper_line);setOnClickListener{startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(b.uri)).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION))}};body.addView(row)}
 fun pickImage(){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),8)}
 override fun onActivityResult(r:Int,c:Int,d:Intent?){super.onActivityResult(r,c,d);if(r==8&&c==RESULT_OK&&d?.data!=null){val u=d.data!!;try{contentResolver.takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION)}catch(_:Exception){};val name=u.lastPathSegment?.substringAfterLast('/')?:"صورة";blocks.add(Block(noteId=id,type="IMAGE",position=blocks.size,uri=u.toString(),name=name));save();loadBlocks()}}
 override fun onPause(){save();super.onPause()}
 fun printNote(){val p=getSystemService(PRINT_SERVICE) as android.print.PrintManager;p.print("دفتر يومي",object:android.print.PrintDocumentAdapter(){override fun onLayout(a:android.print.PrintAttributes?,o:android.print.PrintAttributes?,c:android.os.CancellationSignal?,cb:android.print.PrintDocumentAdapter.LayoutResultCallback?,x:android.os.Bundle?){cb?.onLayoutFinished(android.print.PrintDocumentInfo.Builder("daily_note.pdf").setContentType(android.print.PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).setPageCount(1).build(),true)}override fun onWrite(p:Array<android.print.PageRange>?,f:android.os.ParcelFileDescriptor?,c:android.os.CancellationSignal?,cb:android.print.PrintDocumentAdapter.WriteResultCallback?){try{val doc=android.graphics.pdf.PdfDocument();val page=doc.startPage(android.graphics.pdf.PdfDocument.PageInfo.Builder(226,900,1).create());val cv=page.canvas;cv.drawColor(Color.WHITE);val paint=android.graphics.Paint().apply{textSize=18f;color=Color.BLACK;textAlign=android.graphics.Paint.Align.RIGHT};var y=35f;buildText().split("\n").forEach{if(y<870){cv.drawText(it,215f,y,paint);y+=25}};doc.finishPage(page);doc.writeTo(java.io.FileOutputStream(f!!.fileDescriptor));doc.close();cb?.onWriteFinished(arrayOf(android.print.PageRange.ALL_PAGES))}catch(e:Exception){cb?.onWriteFailed(e.message)}}},null)}
}