package com.saleh12340.quickdailynotebook
import android.Manifest;import android.app.*;import android.bluetooth.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import java.util.*
object ThermalPrinter{
 private val uuid=UUID.fromString("00001101-0000-1000-8000-00805F9B34FB")
 fun choose(c:Activity,text:String){if(android.os.Build.VERSION.SDK_INT>=31&&c.checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){c.requestPermissions(arrayOf(Manifest.permission.BLUETOOTH_CONNECT),91);return}
 val a=c.getSystemService(Context.BLUETOOTH_SERVICE) as BluetoothManager;val dev=a.adapter.bondedDevices.toList();if(dev.isEmpty()){Toast.makeText(c,"لا توجد طابعة Bluetooth مقترنة",Toast.LENGTH_LONG).show();return}
 AlertDialog.Builder(c).setTitle("اختر الطابعة").setItems(dev.map{"${it.name} — ${it.address}"}.toTypedArray()){_,which->send(c,dev[which],text)}.show()}
 private fun send(c:Activity,d:BluetoothDevice,text:String){Thread{try{val s=d.createRfcommSocketToServiceRecord(uuid);s.connect();val out=s.outputStream;out.write(byteArrayOf(0x1B,0x40));out.write(render(text));out.write(byteArrayOf(0x0A,0x0A,0x1D,0x56,0x00));out.flush();out.close();s.close();c.runOnUiThread{Toast.makeText(c,"تم إرسال الإيصال للطابعة",Toast.LENGTH_SHORT).show()}}catch(e:Exception){c.runOnUiThread{Toast.makeText(c,"تعذر الاتصال بالطابعة: ${e.message}",Toast.LENGTH_LONG).show()}}}.start()}
 private fun render(text:String):ByteArray{val w=384;val paint=Paint(Paint.ANTI_ALIAS_FLAG).apply{color=Color.BLACK;textSize=25f;typeface=Typeface.DEFAULT_BOLD;textAlign=Paint.Align.RIGHT};val lines=text.split("\n");val h=maxOf(80,lines.size*34+30);val b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);val cv=Canvas(b);cv.drawColor(Color.WHITE);var y=28f;lines.forEach{cv.drawText(it.take(34),w-8,y,paint);y+=34};val bytes=java.io.ByteArrayOutputStream();bytes.write(byteArrayOf(0x1B,0x61,0x02));for(y0 in 0 until h step 24){bytes.write(byteArrayOf(0x1B,0x2A,33,(w/8).toByte(),0));for(x in 0 until w/8){var v=0;for(bit in 0..7){val yy=y0+bit;if(yy<h){val px=b.getPixel(x*8+bit,yy);if(Color.red(px)<180)v=v or (1 shl (7-bit))}};bytes.write(v)};bytes.write(0);bytes.write(0x0A)};return bytes.toByteArray()}
}